#!/usr/bin/env python
# -*- coding:utf-8 -*-


"""
A minimal front end to the Docutils Publisher, producing XeLaTeX source code.
"""

try:
    import locale
    locale.setlocale(locale.LC_ALL, '')
except:
    pass

from docutils.core import publish_cmdline

from tecrst.xetex import Writer


description = ('Generates XeLaTeX documents from standalone reStructuredText '
               'sources. '
               'Reads from <source> (default is stdin) and writes to '
               '<destination> (default is stdout).  See '
               '<http://docutils.sf.net/docs/user/latex.html> for '
               'the full reference.')

publish_cmdline(writer=Writer(), description=description)
